apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-config
data:
    tasks.py: |
      from locust import HttpLocust, TaskSet, between
      def index(l):
        l.client.get("/")
      class UserBehavior(TaskSet):
        tasks = {index: 1}
      class WebsiteUser(HttpLocust):
        task_set = UserBehavior
        wait_time = between(5.0, 9.0)