apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: locustloadtests.hack.berlin
spec:
  group: hack.berlin
  names:
    kind: LocustLoadTest
    listKind: LocustLoadTestList
    plural: locustloadtests
    singular: locustloadtest
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1beta1
    served: true
    storage: true
