apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bench-operator
  template:
    metadata:
      labels:
        name: bench-operator
    spec:
      serviceAccountName: bench-operator
      containers:
        - name: bench-operator
          image: versus42/contsolhack
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bench-operator"
